#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse, os, sys, subprocess, shlex, yaml

def load_cfg(path):
    with open(path, "r") as f:
        return yaml.safe_load(f)

def run(cmd, dry_run=False, cwd=None):
    print("[CMD]", cmd)
    if dry_run:
        return 0
    proc = subprocess.run(shlex.split(cmd), cwd=cwd)
    return proc.returncode

def repo_root():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

def main():
    ap = argparse.ArgumentParser(description="Fine-tune sequence model (SeqML)")
    ap.add_argument("--config", required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    cfg = load_cfg(args.config)
    root = repo_root()
    py = sys.executable

    P = cfg["paths"]
    SQ = cfg.get("seqml", {})
    lora = SQ.get("lora", {})

    out_dir = os.path.join(P.get("output_dir","outputs"), "seqml")
    os.makedirs(out_dir, exist_ok=True)

    # Expect mutants.csv already exists (generated by e2e or prepare_mutants)
    mutants_csv = os.path.join(out_dir, "..", "mutants.csv")
    if not os.path.exists(mutants_csv):
      # fallback: assume user supplied a prepared csv path in config
      mutants_csv = SQ.get("train_csv", mutants_csv)

    cmd = (
        f"{py} packages/seqml/scripts/train.py "
        f"--train-csv {mutants_csv} "
        f"--model {SQ.get('model_name','t5-small')} "
        f"--epochs {SQ.get('epochs',3)} "
        f"--out-dir {out_dir} "
        f"--lora-r {lora.get('r',8)} "
        f"--lora-alpha {lora.get('alpha',16)} "
        f"--lora-dropout {lora.get('dropout',0.05)}"
    )
    if run(cmd, args.dry_run, cwd=root) != 0: sys.exit(1)

if __name__ == "__main__":
    main()
